# Generated by Django 3.2.16 on 2022-10-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_tickets', '0002_auto_20221017_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
