# Generated by Django 3.2.16 on 2022-10-18 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        ('buy_tickets', '0003_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='from_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='to_city',
        ),
        migrations.AddField(
            model_name='order',
            name='arrivals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='tickets.tickets'),
        ),
        migrations.AddField(
            model_name='order',
            name='departures',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='tickets.tickets'),
        ),
    ]
