# Generated by Django 3.2.16 on 2022-10-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20221017_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
