# Generated by Django 3.2.16 on 2022-10-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
